openapi: 3.0.3
info:
  title: vos.io public API
  description: |-
    This is the public API to configure, operate and monitor the VOS.IO.  The API is organized in categories.  They are:

    - live
    - origin-engine
    - externalAssetStorage
    - fileTranscode
    - notification
    
  termsOfService: https://www.vos.io/terms/
  contact:
    email: vosio_api@vos.io
  license:
    name: vos.io
    url: https://www.vos.io/licenses/LICENSE-1.0.html
  version: 1.0.0
servers: 
  - url: https://www.vos.io/api
tags:
  - name: live
  - name: origin-engine
  - name: externalAssetStorage
  - name: fileTranscode
  - name: notification
paths:
  /live/v1/cloudsources:
    get:
      summary: List all the Cloud Sources
      tags:
        - live
      description: list all the cloud sources
      operationId: listCloudSources
      security:
      - vosio_auth:
        - write:vosio
        - read:vosio
    post:
      summary: Create a Cloud Source
      tags:
        - live
      description: create a cloud source
      operationId: createCloudSource
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /live/v1/cloudsources/{id}:
    get:
      summary: Get cloud source by Id
      tags:
        - live
      description: Get cloud source by Id
      operationId: getCloudSourcebyId
      security:
      - vosio_auth:
          - write:vosio
          - read:vosio
    put:
      summary: Update a Cloud Source
      tags:
        - live
      description: update a cloud source
      operationId: updateCloudSource
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
    delete:
      summary: Delete a Cloud Source
      tags:
        - live
      description: delete a cloud source
      operationId: deleteCloudSource
      security:
      - vosio_auth:
          - write:vosio
          - read:vosio
  /live/v1/cloudsources/{id}/offline:
    put:
      summary: Action to offline the Cloud Source by id
      tags:
        - live
      description: offline the Cloud Source
      operationId: offlineCloudSource
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /live/v1/cloudsources/{id}/online:
    put:
      summary: Action to online the cloud source by id
      tags:
        - live
      description: online the Cloud Source
      operationId: onlineCloudSource
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /live/v1/images:
    get:
      summary: List all the images
      tags:
        - live
      description: list all the images
      operationId: listImages
      security:
      - vosio_auth:
        - write:vosio
        - read:vosio
    post:
      summary: Create an image
      tags:
        - live
      description: create an image
      operationId: createImage
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio   
  /live/v1/images/{id}:
    get:
      summary: Get image by Id
      tags:
        - live
      description: Get image by Id
      operationId: getImagebyId
      security:
      - vosio_auth:
          - write:vosio
          - read:vosio
    put:
      summary: Update an image
      tags:
        - live
      description: update an image
      operationId: updateImage
      security:
      - vosio_auth:
          - write:vosio
          - read:vosio      
    delete:
      summary: Delete an image
      tags:
        - live
      description: delete an image
      operationId: deleteImage
      security:
      - vosio_auth:
          - write:vosio
          - read:vosio           
  /live/v1/events:
    get:
      summary: List all the live Events
      tags:
        - live
      description: list all the live Events
      operationId: listLiveEvents
      security:
      - vosio_auth:
          - write:vosio
          - read:vosio
    post:
      summary: Create a live Event
      tags:
        - live
      description: create a live Event
      operationId: createLiveEvent
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /live/v1/events/{id}:
    get:
      summary: Get a live Event details
      tags:
        - live
      description: Get a live Event
      operationId: getLiveEventDetails
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
    put:
      summary: Update a live Event
      tags:
        - live
      description: update a live Event
      operationId: updateLiveEvent
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
    delete:
      summary: Delete a live Event
      tags:
        - live
      description: delete a live Event
      operationId: deleteLiveEvent
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /live/v1/events/{id}/offline:
    put:
      summary: Action to offline the live event with id
      tags:
        - live
      description: offline the live event
      operationId: offlineLiveEvent
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio   
  /live/v1/events/{id}/preview:
    put:
      summary: Action to preview the live event with id
      tags:
        - live
      description: preview the live event
      operationId: previewLiveEvent
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /live/v1/events/{id}/goLive:
    put:
      summary: Action to goLive the live event with id
      tags:
        - live
      description: goLive the live event
      operationId: goLiveLiveEvent
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /live/v1/events/{id}/end:
    put:
      summary: Action to end the live event with id
      tags:
        - live
      description: End the live event
      operationId: endLiveEvent
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /live/v1/events/{id}/insertSlate:
    put:
      summary: Action to insert Slate image to the live event with id
      tags:
        - live
      description: insert slate to the live event
      operationId: insertSlateLiveEvent
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /live/v1/events/{id}/removeSlate:
    put:
      summary: Action to remove Slate image to the live event with id
      tags:
        - live
      description: remove slate to the live event
      operationId: removeSlateLiveEvent
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /notification/v1/settings:
    get:
      summary: Notification webhook setting
      tags:
        - notification
      description: returns the notification settings
      operationId: getNotificationSetting
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
    put:
      summary: Update notification settings
      tags:
        - notification
      description: returns the notification settings
      operationId: updateNotificationSettings
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /live/v1/settings:
    get:
      summary: Get live event app settings
      tags:
        - live
      description: returns the live settings
      operationId: getLiveSettings
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
    put:
      summary: Update liveEvents settings
      tags:
        - live
      description: returns the liveEvents settings
      operationId: updateLiveEventSettings
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /origin-engine/v1/streamingCapacity:
    get:
      summary: Get origin streaming capacity related to streaming units reserved.  The streaming units are shared with all Live Events and Dynamic Packaging outputs
      tags:
        - origin-engine
      description: returns the streaming capacity consumption
      operationId: getStreamingCapacityStreamingUnits
      security:
      - vosio_auth:
          - write:vosio
          - read:vosio
    put:
      summary: Update origin steraming capacity streaming units reserved
      tags:
        - origin-engine
      description: returns the Streaming Unit settings
      operationId: updateStreamingUnitSettings
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /externalAssetStorage/v1/storageAccounts:
    get:
      summary: Get the list of dynamic packaging config
      tags:
        - externalAssetStorage
      description: Dynamic Packaging is Package on the Fly (POTF) of multi-bitrate content to streaming formats.  It is tight to a storage account where mp4 or ismv files are located.  Each dynamic packaging configuration can have an account and packaging format/DRM configured.
      operationId: listExternalAssetStorage
      security:
      - vosio_auth:
          - write:vosio
          - read:vosio
    post:
      summary: Create storage account config
      tags:
        - externalAssetStorage
      description: Dynamic Packaging is Package on the Fly (POTF) of multi-bitrate content to streaming formats.  It is tight to a storage account where mp4 or ismv files are located.  Each dynamic packaging configuration can have an account and packaging format/DRM configured.
      operationId: createExternalAssetStorageConfig
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /externalAssetStorage/v1/storageAccounts/{id}:
    get:
      summary: Get storage account details
      tags:
        - externalAssetStorage
      description: get storage acccount details
      operationId: getExternalStorageAccountDetails
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
    put:
      summary: Update Storage Account
      tags:
        - externalAssetStorage
      description: update Storage Account Config
      operationId: updateExternalAssetStorageConfig
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
    delete:
      summary: Delete a Storage Account Config
      tags:
        - externalAssetStorage
      description: delete a storage account config
      operationId: deleteExternalAssetStorageConfig
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /externalAssetStorage/v1/storageAccounts/{id}/playbackUrl:
    get:
      summary: Get playback URL
      tags:
        - externalAssetStorage
      description: get playback URL
      operationId: getPlaybackUrl
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
  /externalAssetStorage/v1/packagingProfileAdvanced:
    get:
      summary: Show External Asset Storage Packaging Profile Config.  It applies to all Storage Accounts
      tags:
        - externalAssetStorage
      description: show packaging profile config
      operationId:
        getExternalAssetStoragePackagingProfileConfig360
      security:
        - vos360_auth:
            - write:vos360
            - read:vos360     
    put:
      summary: Update External Asset Storage Packaging Profile Config
      tags:
        - externalAssetStorage
      description: update packaging profile config
      operationId: updateExternalAssetStoragePackagingProfileConfig360
      security:
        - vos360_auth:
            - write:vos360
            - read:vos360    
  /externalAssetStorage/v1/packagingProfile:
    get:
      summary: Show External Asset Storage Packaging Profile Config.  It applies to all Storage Accounts
      tags:
        - externalAssetStorage
      description: show packaging profile config
      operationId:
        getExternalAssetStoragePackagingProfileConfigIo
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio     
    put:
      summary: Update External Asset Storage Packaging Profile Config
      tags:
        - externalAssetStorage
      description: update packaging profile config
      operationId: updateExternalAssetStoragePackagingProfileConfigIo
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio   
  /fileTranscode/v1/jobs:
    get:
      summary: Get the list of jobs
      tags:
        - fileTranscode
      description: File Transcode is job than transcode single bitrate source media into multi-bitrates media that can be used for playback with Dynamic Packaging as OTT streaming formats
      operationId: listFileTranscodeJobs
      security:
      - vosio_auth:
          - write:vosio
          - read:vosio
    post:
      summary: Create File Transcoding Job
      tags:
        - fileTranscode
      description: File Transcoding Job turns a single bitrate media into multi-bitrates content files for Dynamic Packaging into OTT streaming formats
      operationId: createFileTranscodeJob
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio 
  /fileTranscode/v1/jobs/{id}:
    get:
      summary: Get file transcode job details
      tags:
        - fileTranscode
      description: Get file transcode job
      operationId: getFileTranscodeJobDetails
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
    delete:
      summary: Delete a file transcode job
      tags:
        - fileTranscode
      description: delete a File Transcode Job
      operationId: deleteFileTranscodeJob
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio  
  /fileTranscode/v1/jobs/{id}/state:
    get:
      summary: get File Transcode job state
      tags:
        - fileTranscode
      description: get file transcode job state
      operationId: getFileTranscodeJobState
      security:
        - vosio_auth:
            - write:vosio
            - read:vosio
components:
  securitySchemes:
    vosio_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://vos.io/oauth/authorize
          scopes:
            write:vosio: modify vos.io config
            read:vosio: read your vos.io config
    vos360_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://vos360.vos360.video/oauth/authorize
          scopes:
            write:vos360: modify vos360 config
            read:vos360: read your vos360 config
